apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  TOPIC_NAME: "locations-topic"
  KAFKA_SERVER: "kafka-service.default.svc.cluster.local:9092"
metadata:
  name: db-env
